name: "release_hook"
on: [release]

jobs:
  trigger-hook:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json-extended'
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
